# Generated by Django 4.0.2 on 2022-02-26 18:38

from django.db import migrations, models
import phonenumber_field.modelfields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='avatar',
            field=models.ImageField(default='default/user_default.jpg', upload_to=users.models.img_dir, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Surname'),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
