# Generated by Django 4.0.2 on 2022-02-27 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('text', models.TextField(verbose_name='Article text')),
                ('image', models.ImageField(default='default/article_default.jpg', upload_to='article/', verbose_name='Image')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-address')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': "Article's",
            },
        ),
    ]
